In [1]:
import numpy as np
import pandas as pd
import nltk
import nltk
from nltk.corpus import stopwords
import string

In [2]:
df = pd.read_csv("spam3.csv")
df = df.iloc[:,:2]
df = df.fillna(value="1")
df

EmailText Label
0     Supply Quality China's EXCLUSIVE dimensions at...     1
1                            over. SidLet me know. Thx.     0
2     Dear Friend,Greetings to you.I wish to accost ...     1
3     MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....     1
4             Not a surprising assessment from Embassy.     0
...                                                 ...   ...
7017  With urgent attention !!!!!!>From the Desk of ...     1
7018  ON YOUR INABILITY TO HANDLE THIS TRANSACTION, ...     1
7019  Dear Friend, I am Mrs Nenita Villaran-a citize...     1
7020  \t\t\t\t\t\t  \tBest Wishes,Barrister Anthony ...     1
7021               What exactly are the talking points?     0

[7022 rows x 2 columns]

In [3]:
from nltk.corpus import stopwords

def text_process(mess):
    """
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. Returns a list of the cleaned text
    """
    # Check characters to see if they are in punctuation
    nopunc = [char for char in mess if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # Now just remove any stopwords
    return ' '.join([word for word in nopunc.split() if word.lower() not in stopwords.words('english')])

In [4]:
x = df.EmailText
y = df.Label
y= y.astype('int')

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2 , random_state=1)

In [6]:
x_train.shape

(5617,)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

# instantiate the vectorizer
vect = CountVectorizer()
x_train_dtm = vect.fit_transform(x_train)
x_train_dtm

<5617x64201 sparse matrix of type '<class 'numpy.int64'>'
	with 598924 stored elements in Compressed Sparse Row format>

In [8]:
x_train_dtm = vect.transform(x_train)

In [9]:
x_train_dtm = vect.fit_transform(x_train)

In [10]:
x_train_dtm

<5617x64201 sparse matrix of type '<class 'numpy.int64'>'
	with 598924 stored elements in Compressed Sparse Row format>

In [11]:
x_test_dtm = vect.transform(x_test)
x_test_dtm

<1405x64201 sparse matrix of type '<class 'numpy.int64'>'
	with 141051 stored elements in Compressed Sparse Row format>

In [12]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer()
tfidf_transformer.fit(x_train_dtm)
tfidf_transformer.transform(x_train_dtm)

<5617x64201 sparse matrix of type '<class 'numpy.float64'>'
	with 598924 stored elements in Compressed Sparse Row format>

In [13]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
# from sklearn.naive_bayes import MultinomialNB

pipe2 = Pipeline([('bow', CountVectorizer()), 
                 ('tfid', TfidfTransformer()),  
                 ('model', KNeighborsClassifier(n_neighbors=79))])

In [14]:
pipe2.fit(x_train, y_train)

Pipeline(steps=[('bow', CountVectorizer()), ('tfid', TfidfTransformer()),
                ('model', KNeighborsClassifier(n_neighbors=79))])

In [15]:
y_pred = pipe2.predict(x_test)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cn = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
print(cn)
print(ac)

[[601 153]
 [  5 646]]
0.8875444839857651


In [40]:
def myfunc(value):
    check = pipe2.predict([value])
    if check == 1:
        print("spam")
    elif check == 0:
        print("ham")
value = input("Enter string :")
myfunc(value)

Enter string :how are u
ham


In [18]:
pipe2.predict(["you have won lottery please click the link below to claim your 10 lakh price "])

array([1])

In [19]:
pipe2.predict(["congratulations,you have won lottery, please call our number to claim it"])

array([0])

In [20]:

upipe2.predict(["you won lottery of 10 lakh please click this link to claim "])

array([1])

In [21]:
pipe2.predict(["free free our website give money for free please click this link to claim it"])t

array([1])

In [22]:
pipe2.predict(["you have a won lottery please, click here to claim your lottery"])

array([1])

In [23]:
pipe2.predict(["congratulations you got a car"])()

array([0])

In [24]:
pipe2.predict(["how are you"])

array([0])

In [25]:
pipe2.predict(["i will send a email to your website please check"])

array([0])

In [26]:
pipe2.predict(["i will send a messgae to your mobile check and call me congratulations, you have won lottery of 10 lakh please click to this link claim it"])

array([1])

In [27]:
pipe2.predict(["hello nice to met you , you won the airport thank you, plese come my soap opening and just see dont underestimate of a comon man ok by sallu you won the lottery free ok and claim it click here on this link click here on thisl link click here its frer free free please claim to lottery and call me to the lottery you won 10 lakh lottery and then click here to in link you are the winner "])

array([1])

In [742]:
import joblib
import pickle

In [744]:
joblib.dump(pipe2, "model.pkl")

['model.pkl']

In [745]:
model2 = joblib.load("model.pkl")

In [746]:
model2.predict(["hello nice to met you , you won the airport thank you, plese come my soap opening and just see dont underestimate of a comon man ok by sallu you won the lottery free ok and claim it click here on this link click here on thisl link click here its frer free free please claim to lottery and call me to the lottery you won 10 lakh lottery and then click here to in link you are the winner "])

array([1])

In [747]:
model2.predict(["i will send a email to your website please check"])

array([0])

In [749]:
model2.predict(["hello thank u for calling and i will call you later"])

array([0])

In [751]:
cn = confusion_matrix(y_test, y_pred)
print(cn)

[[601 153]
 [  5 646]]


In [752]:
cn = accuracy_score(y_test, y_pred)
print(cn)

0.8875444839857651
